// Generated by https://quicktype.io

export interface Component {
    id:            number;
    barcode:       string;
    serialNo:      string;
    componentType: string;
    brand:         string;
    model:         string;
    specification: string;
    vendor:        string;
    datePO:        string;
    dateAcquired:  string;
    lastModified:  string;
    assignedID:    number;
}
