// Generated by https://quicktype.io

export interface Employee {
  id:           number;
  employeeCode: string;
  firstName:    string;
  middleName:   string;
  lastName:     string;
  company:      string;
  department:   string;
  domainName:   string;
  anydeskCode:  string;
  position:     string;
}


// Generated by https://quicktype.io

export interface Department {
    id:       number;
    deptCode: string;
    deptName: string;
}
// Generated by https://quicktype.io

export interface Company {
    id:       number;
    compCode: string;
    compName: string;
}

