// Generated by https://quicktype.io
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface AssetAssignedDTO {
    id:                number;
    assetInventoryId:  number;
    assetInventoryDTO: AssetInventoryDTO;
    company:           string;
    department:        string;
    accountabilityNo:  string;

    currentUser:       string;
    remarks:           string;
    lastModified:      string;
}

export interface AssetInventoryDTO {
    id:           number;
    barcode:      string;
    unit:         string;
    serialNo:     string;
    specs:        string;
    vendor:       string;
    warranty:     string;
    datePO:       string;
    dateAcquired: string;
}




